version: "3.7"

networks:
  network.kaboom.mvg-sky.com:
    name: network.kaboom.mvg-sky.com

services:
  ca.kaboom.mvg-sky.com:
    container_name: ca.kaboom.mvg-sky.com
    image: hyperledger/fabric-ca:latest
    labels:
      service: fabric.kaboom.mvg-sky.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kaboom.mvg-sky.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - 7054:7054
      - 17054:17054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ${PWD}/dist/organizations/peerOrganizations/kaboom.mvg-sky.com/fabric-ca:/etc/hyperledger/fabric-ca-server
    networks:
      - network.kaboom.mvg-sky.com
