version: "3.7"

networks:
  test:
    name: fabric_test

services:
  peer0.org1.example.com:
    networks:
      - test

  cli.org1:
    container_name: cli.org1
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ${PWD}/.dist/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/.dist/organizations
      - ${PWD}/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ${PWD}/organizations/org1/config/core-config.yaml:/etc/hyperledger/peercfg/core.yaml
    depends_on:
      - peer0.org1.example.com
    networks:
      - test
