version: "3.7"

services:
  mvg-sky-kaboom:
    container_name: mvg-sky-kaboom
    image: mvg-sky-kaboom
    restart: always
    build: .
    ports:
        - "5000:3000"
    environment:
      - PORT=3000
      - VUE_APP_API_URL=http://api.mvg-sky.com/api
